### ISSUE TITLE
I get an error when running 

### ISSUE THREAD

**Issue by disco1111** [TheHWcave/OWON-XDM1041#3]
Hi
looks like a great little app, on windows 10 enterprise 2019 ltsc x64
I get this error..
Probably something I'm doing wrong

Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
============= RESTART: C:\Users\Dean Workshop 2\Desktop\xdm1041.py =============
Traceback (most recent call last):
  File "C:\Users\Dean Workshop 2\Desktop\xdm1041.py", line 24, in <module>
    import serial
ModuleNotFoundError: No module named 'serial'
>>>

**Comment by TheHWcave** [comment]
You need to install PySerial 
https://pythonhosted.org/pyserial/pyserial.html#installation
Probably should have added this requirement to the documentation (sorry)

    On Monday, 28 March 2022, 14:18:48 BST, disco1111 ***@***.***> wrote:  
 
 


Hi
looks like a great little app, on windows 10 enterprise 2019 ltsc x64
I get this error..
Probably something I'm doing wrong

Python 3.8.10 (tags/v3.8.10:3d8993a, May 3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.







============= RESTART: C:\Users\Dean Workshop 2\Desktop\xdm1041.py =============
Traceback (most recent call last):
File "C:\Users\Dean Workshop 2\Desktop\xdm1041.py", line 24, in 
import serial
ModuleNotFoundError: No module named 'serial'

**Comment by disco1111** [comment]
This worked a treat! 
Thankyou
Great little app

I know it's not an issue per se, but a few things would make it even more awesome..
  1, time stamp column in the csv taken from host pc
  2, ability to record faster than 1 second interval (not useful to me but sure it would be to some?)

Again thanks for your work on this it works great
Best
Dean


> You need to install PySerial https://pythonhosted.org/pyserial/pyserial.html#installation Probably should have added this requirement to the documentation (sorry) On Monday, 28 March 2022, 14:18:48 BST, disco1111 ***@***.***> wrote: Hi looks like a great little app, on windows 10 enterprise 2019 ltsc x64 I get this error.. Probably something I'm doing wrong Python 3.8.10 (tags/v3.8.10:3d8993a, May 3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32 Type "help", "copyright", "credits" or "license()" for more information. ============= RESTART: C:\Users\Dean Workshop 2\Desktop\xdm1041.py ============= Traceback (most recent call last): File "C:\Users\Dean Workshop 2\Desktop\xdm1041.py", line 24, in import serial ModuleNotFoundError: No module named 'serial' — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
